### ISSUE TITLE
Submitting a form without javascript enabled

### ISSUE THREAD

**Issue by treffynnon** [kirkouimet/jformer#1]
Looking at the code produced by the jFormer PHP I cannot see how the form can be processed with out the inclusion of javascript. This is because unless I am missing something you cannot submit a form without javascript as the submit input is of `type="button"` and not `type="submit"`.

**Comment by detain** [comment]
The form in general is not meant to be submitted without javascript.    In general none of this will work without javascript., although maybe adding the ability to generate a non-js version of the form for a  < noscript >  </ noscript > block would be a neat feature, not sure how might it might get used or how well  <  noscript  > blocks are even used or supported anymore in browsers.
