### ISSUE TITLE
Wrong Directory Path

### ISSUE THREAD

**Issue by selbyk** [kirkouimet/jformer#9]
I am uncertain if this is the same issue posted below this, but just in case:
Instead of using the webserver path ( http://domain.com/Login.php ) it uses the full directory path ( http://domain.com/home/name/public_html/Login.php ) resulting in a 404 post. There is no documentation, and I couldn't figure it out by tracing the code. Is there something simple I am missing?

**Comment by selbyk** [comment]
My mistake, should have just read through what documentation there is. -.-'

**Comment by kirkouimet** [comment]
No prob - best of luck selbyk!

**Comment by selbyk** [comment]
jFormer is definitely a nifty addition to my tool set. Thanks for the good work!
